### ISSUE TITLE
Tutorial improvement & deduplication ideas

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit#10680]
Built off of https://github.com/Qiskit/qiskit-tutorials/issues/1473.

## Quantum circuits

- [ ] [qiskit intro](https://github.com/Qiskit/qiskit-metapackage/blob/master/docs/intro_tutorial1.rst), [circuit_basics](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits/01_circuit_basics.ipynb), and [getting_started_with_qiskit](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits/1_getting_started_with_qiskit.ipynb) are all very similar: https://github.com/Qiskit/qiskit-terra/issues/10315
- [ ] [plotting_data_in_qiskit](https://qiskit.org/documentation/tutorials/circuits/2_plotting_data_in_qiskit.html) is replaced by api reference examples: https://github.com/Qiskit/qiskit-terra/issues/8567
- [ ] [summary_of_quantum_operations](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits/3_summary_of_quantum_operations.ipynb) is replaced by api reference examples: https://github.com/Qiskit/qiskit-terra/pull/7354

## Advanced circuits

- [ ] [advanced_circuits](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/01_advanced_circuits.ipynb), more like api reference code examples or how-to guide, should be converted to those content type
- [ ] [operators_overview](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/02_operators_overview.ipynb), more like api reference code examples or how-to guide, should be converted to those content type
- [ ] [advanced_circuit_visualization](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/03_advanced_circuit_visualization.ipynb), most of the content is covered by one of the how-to guide here: https://github.com/Qiskit/qiskit-terra/pull/8624
- [ ] [transpiler_passes_and_passmanager](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/04_transpiler_passes_and_passmanager.ipynb), should be converted to a how-to guide
- [ ] [pulse_gates](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/05_pulse_gates.ipynb), should be converted to a how-to guide
- [ ] [building_pulse_schedules](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/06_building_pulse_schedules.ipynb), should be converted to a how-to guide
- [ ] [pulse_scheduler](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/07_pulse_scheduler.ipynb), should be converted to a how-to guide
- [ ] [gathering_system_information](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/08_gathering_system_information.ipynb), should be converted to a how-to guide. The content is about BackendV1, should be updated to BackendV2 equivalent: https://github.com/Qiskit/qiskit-terra/issues/10317

## Operators -> Remove in 0.45

Maybe deprecate in 0.44 now.

- [ ] operator_flow: remove since optflow is deprecated. 
- [ ] gradients_framework: remove since optflow is deprecated.

**Comment by jakelishman** [comment]
I'll transfer this issue over to Qiskit/documentation since I'm fairly sure it belongs there now, just in case there's anything in this that you still want to track (I suspect you've got other trackers, though).
