### ISSUE TITLE
Pulse Compiler and IR

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit#10759]
Goal:
Introducing a modern compiler for pulse module and dedicated IR for it.

RFC:
https://github.com/Qiskit/RFCs/blob/master/0012-Pulse-Compiler-and-IR.md

- [x] Logical elements and frames #10694 
- [x] PulseIR - #11767
  - [x] Followup https://github.com/Qiskit/qiskit/pull/11951
- [x] Support logical element and frame representation in pulse instructions https://github.com/Qiskit/qiskit/pull/11726
- [x] Pulse compiler https://github.com/Qiskit/qiskit/pull/11743
- [x] Compilation passes
  - [x] Sequence https://github.com/Qiskit/qiskit/pull/11980
  - [x] Schedule https://github.com/Qiskit/qiskit/pull/11981
- [ ] Re-routing existing compilation tasks to the compiler

**Comment by eliarbel** [comment]
I assume this should remain open for the other tasks to be completed

**Comment by nkanazawa1989** [comment]
Thanks Eli!

**Comment by 1ucian0** [comment]
`qiskit.pulse` was deprecated in 1.3 and removed in 2.0. It has not been supported since 1.4 reached end-of-life in April 2026. Closing this issue as `not planned`.
