### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit#10887]
This issue tracks various components that need to happen before we can be said to fully support Python 3.12.  Notably, we will _automatically_ have wheels available for Python 3.12 already, as since #10120 we've built our wheels against the stable Python C API, which means our released wheels should already be ABI compatible with Python 3.12.  However, not all our dependencies will have pre-built wheels for Python 3.12.

```[tasklist]
### Binary dependencies need to release 3.12 wheels
- [x] Numpy (as of 1.26.0)
- [x] Scipy (as of 1.11.2)
- [x] psutil (as of 5.9.4 it's released abi3 wheels)
- [x] Rustworkx (Qiskit/rustworkx#986)
- [x] Symengine (https://github.com/symengine/symengine-wheels/issues/11)
```

```[tasklist]
### Developer dependencies with problems
- [x] `testtools` fails to import due to the removal of `distutils`.  Should be fixed in next release. (testing-cabal/testtools#352, testing-cabal/testtools#353)
- [x] `stestr` complains that "run is not an 'stestr' command" with Python 3.12.  This turned out to be a knock-on effect of the `testtools` problem above.
- [x] `python-subunit` uses deprecated `datetime.datetime.utcnow`, issuing warnings that fail our suite during collection.  We can add skips for those warnings if necessary.  See testing-cabal/subunit#71.
```

```[tasklist]
### Internal to Qiskit
- [ ] We have problems with Numpy 1.25+ in some isometry code, but will need to support 1.26 for Python 3.12.  See #10305, numpy/numpy#24000.
- [ ] We have problems with Scipy 1.11.0+ on Windows, most likely pre-existing.  See #10345.
- [x] Use of deprecated `ast` features. See #10886
```

**Comment by garrison** [comment]
There are now Python 3.12 wheels for symengine 0.11.0, but Qiskit is still pinned to `symengine>=0.9, <0.10`.  Indeed, when I try `pip install "symengine>=0.9, <0.10"` under Python 3.12, I see the following error:

```
Collecting symengine<0.10,>=0.9
  Using cached symengine-0.9.2.tar.gz (85 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['cmake', 'symengine'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Without the version restriction, it downloads and installs the new wheel.

So, this pin may prevent Qiskit from working with Python 3.12, unless Python 3.12 wheels for older symengine versions were to appear as well.
