### ISSUE TITLE
Implementation of manual classical variables: RFC 0019

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit#10922]
### What should we add?

This is the tracking epic for [RFC `0019`: Variable-declaration and storage representation in Qiskit](https://github.com/Qiskit/RFCs/blob/master/0019-classical-stores.md).  Details of the proposal are in the linked document.  Since the tasklist doesn't show linked PRs, I'm just assigning myself to issues as I open a PR that closes them to give a neater visual indication.

```[tasklist]
### Required
- [ ] #10923
- [ ] https://github.com/Qiskit/qiskit/issues/10939
- [ ] #10924
- [ ] https://github.com/Qiskit/qiskit/issues/10940
- [ ] #10925
- [ ] #10926
- [ ] #10927
- [ ] #10929
- [ ] #10930
- [ ] #10931
- [ ] https://github.com/Qiskit/qiskit/issues/10938
- [ ] https://github.com/Qiskit/qiskit/issues/12332
- [ ] Add changelog entry for manual variable work (closes this epic)
```

```[tasklist]
### Additional circuit methods
- [ ] https://github.com/Qiskit/qiskit/issues/10959
- [ ] https://github.com/Qiskit/qiskit/issues/10960
- [ ] https://github.com/Qiskit/qiskit/issues/10932
- [ ] https://github.com/Qiskit/qiskit/issues/10933
- [ ] https://github.com/Qiskit/qiskit/issues/10934
- [ ] https://github.com/Qiskit/qiskit/issues/10935
- [ ] https://github.com/Qiskit/qiskit/issues/10936
```

```[tasklist]
### Long term required, not necessary for 0.45
- [ ] https://github.com/Qiskit/qiskit/issues/10937
```

**Comment by jakelishman** [comment]
Current dependency DAG of the created PRs, where an arrow from A to B means "A depends on B".

In theory all the links are clickable, but I found it finicky unless you control/command-click to open in a new tab.

```mermaid
stateDiagram-v2

direction BT

classDef merged fill:#8250df,color:white,
classDef unmerged fill:#1f883d,color:white


state "<a href='https://github.com/Qiskit/qiskit/pull/10944'><span style='color:white'>Add representation to <pre>Var</pre> (#10944)
</span></a>" as 10944
state "<a href='https://github.com/Qiskit/qiskit/pull/10946'><span style='color:white'>Add <pre>Store</pre> instruction (#10946)
</span></a>" as 10946
state "<a href='https://github.com/Qiskit/qiskit/pull/10962'><span style='color:white'>Add <pre>QuantumCircuit</pre> var-handling methods (#10962)
</span></a>" as 10962
state "<a href='https://github.com/Qiskit/qiskit/pull/10963'><span style='color:white'><pre>QuantumCircuit</pre> copy methods (#10963)
</span></a>" as 10963
state "<a href='https://github.com/Qiskit/qiskit/pull/10974'><span style='color:white'><pre>QuantumCircuit</pre> append control flow (#10974)
</span></a>" as 10974
state "<a href='https://github.com/Qiskit/qiskit/pull/10975'><span style='color:white'><pre>ControlFlowOp</pre> write-detection helper (#10975)
</span></a>" as 10975
state "<a href='https://github.com/Qiskit/qiskit/pull/10977'><span style='color:white'>Control-flow builder support (#10977)
</span></a>" as 10977


class keyMerged merged
class keyUnmerged unmerged

keyUnmerged --> keyMerged

class 10944 merged
class 10946 merged
class 10962 merged
class 10963 merged
class 10974 merged
class 10975 unmerged
class 10977 unmerged

10946 --> 10944
10962 --> 10946
10963 --> 10962
10974 --> 10963
10975 --> 10974
10977 --> 10974
```

**Comment by jakelishman** [comment]
Pushing this from 0.45 because there are some further internal API considerations about how the transpiler should reason about classical-memory access. The system is already at the limits of special casing, and with me needing / wanting to add in a read/write memory-access split for variables into the transpiler, there's more considerations to be made about how downstream passes will work.  There's no immediate dependents on this work being in 0.45, because it's all internal stepping stones for Qiskit 1.0 work, not stuff that's supported immediately on hardware.

**Comment by jakelishman** [comment]
All merged PRs are reverted by #11667 for 1.0.
