### ISSUE TITLE
Move preset pass manager transpiler passes to rust

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#12208]
### What should we add?

As part of our ongoing effort to migrate more of the rust code for better runtime performance and efficiency we are looking to migrate all the transpiler passes in the preset pass managers to be written in rust. We will still primarily use the python interface for passes as this is a critical part of the transpiler, but the default passes we use should execute solely in rust space and the python portion should just control the dispatch of the rust function.

This is blocked on #11721 and in many cases on #12205 too

The current list of passes involved for this are tracked here:

### Tasks
- [ ] https://github.com/Qiskit/qiskit/issues/12211
- [ ] https://github.com/Qiskit/qiskit/issues/12248
- [ ] https://github.com/Qiskit/qiskit/issues/12249
- [ ] https://github.com/Qiskit/qiskit/issues/12250
- [ ] https://github.com/Qiskit/qiskit/issues/12251
- [ ] https://github.com/Qiskit/qiskit/issues/12253
- [ ] https://github.com/Qiskit/qiskit/issues/12252
- [ ] https://github.com/Qiskit/qiskit/issues/12254
- [ ] https://github.com/Qiskit/qiskit/issues/12255
- [ ] https://github.com/Qiskit/qiskit/issues/12336
- [ ] https://github.com/Qiskit/qiskit/issues/12337
- [ ] https://github.com/Qiskit/qiskit/issues/12256
- [ ] https://github.com/Qiskit/qiskit/issues/12257
- [ ] https://github.com/Qiskit/qiskit/issues/12258
- [ ] https://github.com/Qiskit/qiskit/issues/12259
- [ ] https://github.com/Qiskit/qiskit/issues/12260
- [ ] https://github.com/Qiskit/qiskit/issues/12261
- [ ] https://github.com/Qiskit/qiskit/issues/12262
- [ ] https://github.com/Qiskit/qiskit/issues/12263
- [ ] https://github.com/Qiskit/qiskit/issues/12264
- [ ] https://github.com/Qiskit/qiskit/issues/12265
- [ ] https://github.com/Qiskit/qiskit/issues/12266
- [ ] https://github.com/Qiskit/qiskit/issues/12267
- [ ] https://github.com/Qiskit/qiskit/issues/12268
- [ ] https://github.com/Qiskit/qiskit/issues/12269
- [ ] https://github.com/Qiskit/qiskit/issues/12270
- [ ] https://github.com/Qiskit/qiskit/issues/12271
- [ ] https://github.com/Qiskit/qiskit/issues/12272
- [ ] https://github.com/Qiskit/qiskit/issues/12273
- [ ] https://github.com/Qiskit/qiskit/issues/12274
- [ ] Port `MinimumPoint` to Rust (may not be not needed)
- [ ] https://github.com/Qiskit/qiskit/issues/12275
- [ ] https://github.com/Qiskit/qiskit/issues/12280
- [ ] https://github.com/Qiskit/qiskit/issues/12279
- [ ] https://github.com/Qiskit/qiskit/issues/12277
- [ ] https://github.com/Qiskit/qiskit/issues/12276
- [ ] https://github.com/Qiskit/qiskit/issues/12247
- [ ] #14620 

I included passes that are primarily written in rust because there is still some python side interaction because we don't have #12205 and #11721 yet. (this is current as of 04-18-2024, we should update this if we make changes to the preset pass managers)

**Comment by mtreinish** [comment]
This issue is functionally complete, we are operating the preset pass managers fully in rust space and from C now. There isn't anything left for us to port. The passes listed here that are left are either optional in the preset pass manager or are no longer used by default.
