### ISSUE TITLE
Port built-in synthesis algorithms to rust

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#12212]
### What should we add?

Right now in Qiskit we have a synthesis library that provides numerous methods for synthesizing various high level objects into circuits. As part of our effort to migrate more of Qiskit's code into rust for better runtime performance and efficiency  we need to look at migrating these functions to Rust.

Until we have an implementation complete for #12205 the full path for this will be potentially limited. But we can work on this in parallel to #12205 and return a "circuit sequence" like we currently do in [2q unitary synthesis](https://github.com/Qiskit/qiskit/blob/d10f9a0fe1f73cde5b66e49af880a6f7816f131f/crates/accelerate/src/two_qubit_decompose.rs#L1208-L1213) and [1q unitary synthesis](https://github.com/Qiskit/qiskit/blob/d10f9a0fe1f73cde5b66e49af880a6f7816f131f/crates/accelerate/src/euler_one_qubit_decomposer.rs#L68-L73) (we likely can reuse `TwoQubitGateSequence` from 2q synthesis for >2q circuits as long as it's composed of just standard library gates) and then construct the circuit or dag in python space until we finish #12205.

This will potentially be a blocker for #12211 as we can't leverage a rust implementation of the pass fully if we need to call out to python to perform the synthesis.

The current list of synthesis methods are:

### Tasks
- [x] https://github.com/Qiskit/qiskit/issues/12224
- [x] https://github.com/Qiskit/qiskit/issues/12225
- [x] https://github.com/Qiskit/qiskit/issues/12226
- [x] https://github.com/Qiskit/qiskit/issues/12227
- [x] https://github.com/Qiskit/qiskit/issues/12228
- [x] https://github.com/Qiskit/qiskit/issues/12229
- [ ] https://github.com/Qiskit/qiskit/issues/12230
- [x] https://github.com/Qiskit/qiskit/issues/12231
- [ ] https://github.com/Qiskit/qiskit/issues/12232
- [x] https://github.com/Qiskit/qiskit/issues/12233
- [x] https://github.com/Qiskit/qiskit/issues/12234
- [x] https://github.com/Qiskit/qiskit/issues/12235
- [ ] https://github.com/Qiskit/qiskit/issues/12236
- [ ] https://github.com/Qiskit/qiskit/issues/12237
- [ ] https://github.com/Qiskit/qiskit/issues/12238
- [ ] https://github.com/Qiskit/qiskit/issues/12239
- [ ] https://github.com/Qiskit/qiskit/issues/12240
- [ ] https://github.com/Qiskit/qiskit/issues/12241
- [ ] https://github.com/Qiskit/qiskit/issues/12242
- [ ] https://github.com/Qiskit/qiskit/issues/12243
- [x] https://github.com/Qiskit/qiskit/issues/12244
- [x] https://github.com/Qiskit/qiskit/issues/12245
- [x] https://github.com/Qiskit/qiskit/issues/12213
- [x] ~`aqc`? (this one might not be necessary or too difficult for the scope of this issue and isn't critical).~
- [ ] https://github.com/Qiskit/qiskit/issues/12005
- [x] https://github.com/Qiskit/qiskit/issues/12008
- [x] https://github.com/Qiskit/qiskit/issues/12004
- [x] https://github.com/Qiskit/qiskit/pull/9185
- [x] https://github.com/Qiskit/qiskit/issues/12330
- [x] https://github.com/Qiskit/qiskit/issues/12907
- [x] #13930
