### ISSUE TITLE
deprecate StochasticSwap 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#12552]
`StochasticSwap` is currently use in optmization level 0 and superseded by SabreSwap.
 - [x] remove from level 0 in 1.2 https://github.com/Qiskit/qiskit/pull/12806
 - [ ] deprecate in 1.2/1.3
 - [ ] remove it in 2.0
 - [ ]  close dangling issues, like https://github.com/Qiskit/qiskit/issues/4094

**Comment by weechinghwa** [comment]
Hi, I am interested in taking up this issue.

**Comment by 1ucian0** [comment]
This is more of an epic than an issue (tagging as such). Would you like to help with any of the items? I can take `remove from level 0 in 1.2` because it is time sensitive.

**Comment by weechinghwa** [comment]
I am interested in `deprecate 1.2/1.3`, but this is rather new to me. 
Could you provide some keywords or guides to help me understand it thoroughly from A to Z.

**Comment by 1ucian0** [comment]
> Could you provide some keywords or guides to help me understand it thoroughly from A to Z.

I think a good starting point is https://github.com/Qiskit/qiskit/blob/main/CONTRIBUTING.md#adding-deprecation-warnings

Feel free to create a draft PR soon, so we can discuss it more concretely.
