### ISSUE TITLE
Port `circuit_to_dag` to Rust

### ISSUE THREAD

**Issue by raynelfss** [Qiskit/qiskit#13001]
### What should we add?

With #12550 getting merged soon, we should be thinking of moving the ``circuit_to_dag`` converter into Rust. This issue will keep track of the progress on this effort and describe the designated roadmap.

```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/qiskit/pull/12550
- [ ] https://github.com/Qiskit/qiskit/pull/13006
- [ ] #13002
- [ ] #13003
- [ ] #13004
- [ ] ``circuit_to_dag`` method exposed to Python while using ``DAGCIrcuit::from_circuit_data`` to perform the conversion.
```
