### ISSUE TITLE
Deprecate in 1.4 the pending deprecations from the 1.* cycle

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#13589]
The following functions/methods/classes are annotated as pending deprecations (probably, because the alternative was introduced in the same release):

**1.1**: https://github.com/Qiskit/qiskit/pull/13601 They should be moved to deprecations in 1.4  -> https://github.com/Qiskit/qiskit/pull/13601
- [x] `qiskit/visualization/pulse_v2/interface.py:35` (`draw`)
- [x] `qiskit/visualization/timeline/interface.py:33` (`draw`)
- [x] `qiskit/visualization/timeline/interface.py:34` (`draw`)
- [x] `qiskit/pulse/schedule.py:1696` (`draw`)

**1.2**: https://github.com/Qiskit/qiskit/pull/13603 They should be moved to deprecations in 1.4 -> https://github.com/Qiskit/qiskit/pull/13603
- [x]  `qiskit/synthesis/evolution/suzuki_trotter.py:61` (`__init__`)
- [x]  `qiskit/synthesis/evolution/qdrift.py:44` (`__init__`)
- [x]  `qiskit/synthesis/evolution/product_formula.py:45` (`__init__`)

**1.3**: https://github.com/Qiskit/qiskit/pull/13604 Keep them as deprecated during the 2.* cycle -> https://github.com/Qiskit/qiskit/pull/13604

- [ ] `qiskit/circuit/library/hidden_linear_function.py:71` (`__init__`)
- [ ] `qiskit/circuit/library/graph_state.py:60` (`__init__`)
- [ ] `qiskit/circuit/library/iqp.py:65` (`__init__`)
- [ ] `qiskit/circuit/library/fourier_checking.py:56` (`__init__`)
- [ ] `qiskit/circuit/library/phase_estimation.py:52` (`__init__`)
- [ ] `qiskit/circuit/library/overlap.py:62` (`__init__`)
- [ ] `qiskit/circuit/library/grover_operator.py:426` (`__init__`)
- [ ]  - `qiskit/circuit/library/generalized_gates/diagonal.py:37` (`__init__`)
- [ ]  - `qiskit/circuit/library/generalized_gates/linear_function.py:229` (`synthesize`)
- [ ]  - `qiskit/circuit/library/generalized_gates/permutation.py:31` (`__init__`)
- [ ]  - `qiskit/circuit/library/generalized_gates/gms.py:80` (`__init__`)
- [x]  - `qiskit/circuit/library/generalized_gates/mcmt.py:52` (`__init__`) https://github.com/Qiskit/qiskit/pull/13584
- [x]  - `qiskit/circuit/library/generalized_gates/mcmt.py:159` (`__init__`) https://github.com/Qiskit/qiskit/pull/13584
- [ ]  - `qiskit/circuit/library/basis_change/qft.py:75` (`__init__`)
- [ ]  - `qiskit/circuit/library/data_preparation/pauli_feature_map.py:410` (`__init__`)
- [ ]  - `qiskit/circuit/library/data_preparation/_zz_feature_map.py:98` (`__init__`)
- [ ]  - `qiskit/circuit/library/data_preparation/_z_feature_map.py:78` (`__init__`)
- [ ]  - `qiskit/circuit/library/boolean_logic/quantum_xor.py:32` (`__init__`)
- [ ]  - `qiskit/circuit/library/boolean_logic/quantum_and.py:54` (`__init__`)
- [ ]  - `qiskit/circuit/library/boolean_logic/inner_product.py:65` (`__init__`)
- [ ]  - `qiskit/circuit/library/boolean_logic/quantum_or.py:55` (`__init__`)
- [ ]  - `qiskit/circuit/library/arithmetic/adders/adder.py:45` (`__init__`)
- [ ]  - `qiskit/circuit/library/arithmetic/multipliers/multiplier.py:49` (`__init__`)
- [ ]  - `qiskit/circuit/library/standard_gates/x.py:1174` (`get_num_ancilla_qubits`)
- [ ]  - `qiskit/circuit/library/standard_gates/x.py:1286` (`__init__`)
- [ ]  - `qiskit/circuit/library/standard_gates/x.py:1341` (`__init__`)
- [ ]  - `qiskit/circuit/library/standard_gates/x.py:1431` (`__init__`)
- [ ]  - `qiskit/circuit/library/n_local/n_local.py:306` (`__init__`)
- [ ]  - `qiskit/circuit/library/n_local/efficient_su2.py:194` (`__init__`)
- [ ]  - `qiskit/circuit/library/n_local/real_amplitudes.py:236` (`__init__`)
- [ ]  - `qiskit/circuit/library/n_local/pauli_two_design.py:170` (`__init__`)
- [ ]  - `qiskit/circuit/library/n_local/excitation_preserving.py:215` (`__init__`)
- [ ]  - `qiskit/circuit/library/n_local/two_local.py:140` (`__init__`)

**Comment by Cryoris** [comment]
We need to discuss whether we want to remove the circuit library objects for 2.0 -- I think the sentiment currently is to keep them for the 2.* cycle, since they were heavily used and we might want to allow for a longer grace period before removing them fully.

**Comment by jakelishman** [comment]
1.4 is out the door, and all the checkboxes in this issue are either done, or we decided to leave them in place throughout 2.x. I'll close this epic now.
