### ISSUE TITLE
Single classical bit conditioning breaks various functions

### ISSUE THREAD

**Issue by TharrmashasthaPV** [Qiskit/qiskit#6475]
### Information

- **Qiskit Terra version**: 0.18.0.dev0+f6b2c43
- **Python version**: 3.7

### What is the current behavior?

The PR #6018 enables classical conditioning of gates on individual bits. However, as mentioned in that PR, this new feature breaks the following functions:

- [ ] Condition value validation required. Currently only the non-negativity condition of the condition value is checked. So, passing on any float or Boolean (for creg) also get accepted as a valid condition value which is not quite right. Also, bit length of the condition value is also not checked i.e., passing a `m` bit integer as the condition value for condition on a creg of `n` classical bits (where `m>n`) does not raise error .
- [x] All the drawers break when trying to draw a circuit that contains gates with classical conditioning on a single cbit. ( PR in review. Check #6261 , #6248 and #6259  )
- [ ] `qc.qasm()` breaks when circuit `qc` contains gates with classical conditioning on a single cbit.
- [x] `qc.depth()` also breaks. Refer to https://github.com/Qiskit/qiskit-terra/pull/6018#issuecomment-831598075 ( Fixed in #6476 )
- [x] `disassemble(qc_assembled)` breaks where `qc_assembled` is an assembled `Qobj`. (PR in review. Check #6989 .)
- [x] `qc.num_connected_components` breaks. ( Fixed in #6564.)
- [x] `circuit_to_instruction(qc)` breaks. (PR in review #6537.)
- [ ] `_check_wires_list()` and `substitute_node_with_dag()` methods in qiskit/dagcircuit/dagcircuit.py break.
- [ ] `_is_same_c_conf()` method in `ForwardMatch` and `BackwardMatch` classes in qiskit/transpiler/passes/optimization/template_matching breaks.
- [ ] `run()` method in `ConsolidateBlocks` class in qiskit/transpiler/passes/optimization breaks.
- [x] qpy serialization support (PR in review #6775)

### Suggested solutions

The fixes should be simple. Need to look for parts that have `ClassicalRegister` in condition in these functions and extend them also to cases when `Clbit` is in condition.

**Comment by mtreinish** [comment]
I just added qpy serialization support to the list of things here. It was pointed out to me that trying to dump (and likely load too) a circuit with a single bit condition won't serialize correctly and error. The source is this line:

https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/qpy_serialization.py#L699

because a `Clbit` object doesn't have a name. We might need a qpy format v2 to adjust the condition representation in the serialization format (https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/qpy_serialization.py#L177-L179 ) to handle the lack of a register. Although, thinking out loud we may be able to hack it in by setting the name to be a the `str(index)` of the clbit in the circuit since that is not a valid register name.

**Comment by jakelishman** [comment]
As I understand it, QASM 2 doesn't support conditional operations on anything other than a complete register, so the circuit
```python
import qiskit.circuit.qpy_serialization
from qiskit.circuit import QuantumRegister, QuantumCircuit, ClassicalRegister, Clbit
qr = QuantumRegister(2)
cr = ClassicalRegister(8)
qc = QuantumCircuit(qr, cr)
qc.measure(0, cr[0])
qc.measure(1, cr[1])
qc.x(0).c_if(cr[0], 1)
qc.x(1).c_if(cr, 3)
```
can't be translated into valid QASM 2.  I had intended to go around this by emitting additional 1-bit classical registers and copying the data, but there's also no classical assignment operation, so that doesn't work either.

In theory it is possible to emit valid QASM if the only classical bits used aren't attached to registers, though - instead of binding them all into a single `creg regless[...];` we separate them.  I don't know if we want to put the effort into supporting this if we can't also support subscripts of `ClassicalRegister`?

I suspect the "best" solution to this within the framework of QASM 2 is just to emit `QasmError` in this case?  It doesn't seem very satisfying, though.

**Comment by HuangJunye** [comment]
@TharrmashasthaPV we are planning to release 0.20 soon. Are you planning to fix the rest of issues listed here?

**Comment by jakelishman** [comment]
Closing as obsolete / stale, especially since `Instruction.condition` doesn't exist anymore
