### ISSUE TITLE
Synthesis algorithms for LNN connectivity

### ISSUE THREAD

**Issue by ShellyGarion** [Qiskit/qiskit#9036]
### What should we add?

There are several synthesis algorithms for linear nearest neighbor (LNN) connectivity (that can be embedded into heavy-hex connectivity). These algorithms include:

- [x] Linear (CX) circuits with depth 5n (Kutin et al) #9098 
- [x] Permutations with depth 3n (Kutin et al) #9082 
- [x] CZ circuits with 2q depth 2n+2 (Maslov et al) #9450
- [x] Clifford circuits synthesis by layers (Bravyi and Maslov) #9220 
- [x] CX-CZ circuits with 2q depth 5n (Maslov and Yang) & Clifford synthesis in 2q depth 7n-4 #9932
- [x] StabilizerState synthesis requires only the layers H2 - S1 - CZ1 - H1 - so it has 2q depth 2n+2 (depends on #9543)
- [x] QFT circuits (Fowler et al, Fig 2.b from https://arxiv.org/abs/quant-ph/0402196 ) #11236 
- [x] Reverse permutations in depth 2n+2 (Kutin et al, Section 5, See QFT LNN code) #12181 

These algorithms should be added to `qiskit.synthesis`. 

For completeness, it would be useful to transfer Clifford and CNOT-Dihedral synthesis from `qiskit.quantum_info.synthesis` to `qiskit.synthesis`. 

Further advanced synthesis methods could be added to qiskit ecosystem, and used via the High Level Synthesis plugin, such as the ones suggested in:
https://github.com/Qiskit/qiskit-terra/pull/8548#issuecomment-1255199400
https://github.com/Qiskit/qiskit-terra/issues/8769
